// "use client";

// import { useState, useEffect } from 'react';
// import Fuse from 'fuse.js';

// export default function SearchBar() {
//   const [query, setQuery] = useState("");
//   const [results, setResults] = useState([]);
//   const [fuse, setFuse] = useState(null);

//   useEffect(() => {
//     // Load the index generated by our script
//     fetch('/search-index.json')
//       .then(res => res.json())
//       .then(data => {
//         const options = {
//           keys: ['title', 'tags', 'description'],
//           threshold: 0.3, // Lower = stricter
//         };
//         setFuse(new Fuse(data, options));
//       });
//   }, []);

//   const handleSearch = (e) => {
//     const value = e.target.value;
//     setQuery(value);
//     if (fuse && value.length > 2) {
//       const result = fuse.search(value);
//       setResults(result.map(r => r.item));
//     } else {
//       setResults([]);
//     }
//   };

//   return (
//     <div className="relative">
//       <input
//         type="text"
//         value={query}
//         onChange={handleSearch}
//         placeholder="Search posts..."
//         className="w-full p-2 border rounded-md"
//       />
//       {results.length > 0 && (
//         <ul className="absolute top-full w-full bg-white border mt-1 z-10 shadow-lg">
//           {results.map(post => (
//             <li key={post.slug} className="p-2 hover:bg-gray-100">
//               <a href={`/blog/${post.category}/${post.slug}`}>
//                 <span className="font-bold">{post.title}</span>
//                 <span className="text-xs ml-2 text-gray-500">{post.category}</span>
//               </a>
//             </li>
//           ))}
//         </ul>
//       )}
//     </div>
//   );
// }
